[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn app_3:app --host 0.0.0.0 --port $PORT"
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 200
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1
